FROM ubuntu:20.04

ARG USERNAME=bigred

RUN apt update && \
apt upgrade -y && \
apt clean && rm -rf /var/cache/apt/archives

RUN apt update && \
apt install -y nano tree curl wget ssh jq net-tools iputils-ping sudo openjdk-8-jdk && \
apt clean && \
rm -rf /var/cache/apt/archives

RUN useradd -m -s /bin/bash ${USERNAME} && \
echo "${USERNAME}:${USERNAME}" | chpasswd && \
echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
mkdir /home/${USERNAME}/.ssh && \
ssh-keygen -q -t rsa -N '' -f /home/${USERNAME}/.ssh/id_rsa && \
chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.ssh && \
cat /home/${USERNAME}/.ssh/id_rsa.pub >> /home/${USERNAME}/.ssh/authorized_keys && \
sed -i '/PermitUserEnvironment/c\PermitUserEnvironment yes' /etc/ssh/sshd_config && \
sed -i '/StrictHostKeyChecking/c\StrictHostKeyChecking no' /etc/ssh/ssh_config && \
echo 'sudo /etc/init.d/ssh start' >> /etc/bash.bashrc

USER ${USERNAME}

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

CMD ["/bin/bash"]